#!/usr/bin/env bash
# Install NginX web server on the server, web-01
apt-get update; apt-get -y install nginx
ufw allow "Nginx HTTP"
mkdir /var/www/html
chmod =R 755 /var/www
echo "Hello World!" > /var/www/html/index.html
echo "server {
listen 80 default_server;
listen [::]:80 default_server;
root /etc/nginx/html;
index index.html index.htm;
}" > /etc/nginx/sites-available/default

service nginx restart

