#!/usr/bin/env bash
# Install NginX web server on the server, web-01
apt update && apt install -y nginx
ufw allow "Nginx HTTP"
mkdir /etc/nginx/html
echo "Hello World!" > /etc/nginx/html/index.html
echo "server {
listen 80 default_server;
listen [::]:80 default_server;
root /etc/nginx/html;
index index.html index.htm;
}" > /etc/nginx/sites-available/default

service nginx restart -y

