#!/usr/bin/env bash
# Configure a server to a requirement that fixes the nginx listening port
sed -i 's/listen 8080/listen 80/g' /etc/nginx/sites-enabled/default
sed -i 's/listen \[::\]:8080/listen \[::\]:80/g' /etc/nginx/sites-enabled/default
echo -e "pgrep nginx -o > /run/nginx.pid\nnginx -s reload\necho '' > /run/nginx.pid" | bash
