#!/usr/bin/env bash
# A script that loops from 1 to 10 where "bad luck" is printed for the 4th
# loop iteration, "good luck" is printed for the 8th loop iteration, and
# Best School for the other iterations
i=1
while ((i <= 10))
do
	if ((i == 4))
	then
		echo "bad luck"
	elif ((i == 8))
	then
		echo "good luck"
	else
		echo "Best School"
	fi

	i=$((i+1))
done
